"""Concatenate every Markdown page into one llms-full.txt.

Why this file exists: an agent that can only afford one fetch should still get
the whole picture. llms.txt is the index; llms-full.txt is the entire record.

Order matters. Identity first, then depth, then the changelog last, so a reader
that stops early still has the facts it came for.
"""
import io
import os

# Identity pages, in the order a reader should meet them.
ORDER = [
    "profile.md",
    "experience.md",
    "focus.md",
    "products.md",
    "press.md",
    "faq.md",
    "contact.md",
    "about.md",
    "now.md",
]


def run(site_dir, cfg):
    domain = cfg.get("DOMAIN", "example.com")
    name = cfg.get("FULL_NAME", "")

    parts = [
        "# %s: complete machine-readable record\n" % name,
        "# Every page of https://%s concatenated into one file.\n" % domain,
        "# Generated by scripts/build.py. Do not edit by hand.\n",
        "# Last built: %s\n" % cfg.get("LAST_UPDATED", ""),
    ]

    names = [f for f in ORDER if os.path.exists(os.path.join(site_dir, f))]

    writing = os.path.join(site_dir, "writing")
    if os.path.isdir(writing):
        names += ["writing/" + f for f in sorted(os.listdir(writing)) if f.endswith(".md")]

    # changelog last: it is the least urgent and the most likely to be skipped
    if os.path.exists(os.path.join(site_dir, "changelog.md")):
        names.append("changelog.md")

    for rel in names:
        path = os.path.join(site_dir, rel.replace("/", os.sep))
        parts.append("\n\n" + "=" * 70 + "\n")
        parts.append("# SOURCE: https://%s/%s\n" % (domain, rel))
        parts.append("=" * 70 + "\n\n")
        with io.open(path, encoding="utf-8") as source:
            parts.append(source.read())

    out = "".join(parts)
    with io.open(os.path.join(site_dir, "llms-full.txt"), "w", encoding="utf-8", newline="") as output:
        output.write(out)
    print("  wrote llms-full.txt from %d files (%d bytes)" % (len(names), len(out)))
    return names
