#!/usr/bin/env python3
"""Build a site from template/ + site.config.json into site/.

    python scripts/build.py

Runs six steps:
  1. fill placeholders from site.config.json
  2. publish an explicitly configured, validated A2A v1 Agent Card
  3. index every writing/*.md page in llms.txt
  4. generate an HTML companion for every writing/*.md page
  5. concatenate everything into llms-full.txt
  6. generate sitemap.xml from the public files that were built

Then run scripts/quality_check.py before you deploy.
"""
import io, json, os, re, shutil, stat, sys, tempfile
from urllib.parse import urlsplit, quote

from build_sitemap import validate_last_updated

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE = os.path.join(ROOT, "template")
OUT = os.path.join(ROOT, "site")
CONFIG = os.path.join(ROOT, "site.config.json")
WINDOWS_REPARSE_POINT = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x0400)
REQUIRED_CONFIG = (
    "DOMAIN",
    "FULL_NAME",
    "EMAIL",
    "JOB_TITLE",
    "EMPLOYER",
    "EMPLOYER_URL",
    "LINKEDIN_SLUG",
    "X_HANDLE",
    "ABSENCE_EMPLOYMENT_DATES",
    "ABSENCE_RECORDED_MEDIA",
    "ABSENCE_BYLINED_ARTICLE",
    "LAST_UPDATED",
)


class ScriptSafeJson(str):
    """JSON serialized for direct insertion into an HTML script element."""


def load_config():
    if not os.path.exists(CONFIG):
        sys.exit("No site.config.json. Copy site.config.example.json to site.config.json and fill it in.")
    with io.open(CONFIG, encoding="utf-8") as f:
        cfg = json.load(f)
    if not isinstance(cfg, dict):
        sys.exit("site.config.json must contain an object")
    missing = [key for key in REQUIRED_CONFIG if not isinstance(cfg.get(key), str) or not cfg[key].strip()]
    if missing:
        sys.exit("site.config.json is missing required keys: %s" % ", ".join(missing))
    domain = cfg["DOMAIN"]
    if (
        not isinstance(domain, str)
        or len(domain) > 253
        or not all(re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?", label) for label in domain.split("."))
    ):
        sys.exit("DOMAIN should be a bare hostname, e.g. yourname.com (no https://)")
    try:
        validate_last_updated(cfg["LAST_UPDATED"])
        validate_public_contacts(cfg)
    except ValueError as exc:
        sys.exit(str(exc))
    return cfg


def validate_email_address(value):
    """Validate the supported ASCII dot-atom address, not deliverability."""
    if not isinstance(value, str) or not value.isascii() or len(value) > 254 or value.count("@") != 1:
        raise ValueError("EMAIL must be an ASCII address of at most 254 characters")
    local, domain = value.split("@")
    atom = r"[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+"
    if len(local) > 64 or not re.fullmatch(atom + r"(?:\." + atom + r")*", local):
        raise ValueError("EMAIL local part must be a dot-atom of at most 64 characters")
    labels = domain.split(".")
    label_pattern = r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    if len(domain) > 253 or len(labels) < 2 or not all(re.fullmatch(label_pattern, label) for label in labels):
        raise ValueError("EMAIL domain must contain nonempty DNS labels of at most 63 characters without edge hyphens")


def validate_public_contacts(cfg):
    """Reject executable URLs and ambiguous contact routes before publishing."""
    validate_email_address(cfg.get("EMAIL"))
    for key, pattern in (("LINKEDIN_SLUG", r"[A-Za-z0-9_-]+"),
                         ("X_HANDLE", r"[A-Za-z0-9_]+")):
        if not isinstance(cfg.get(key), str) or not re.fullmatch(pattern, cfg[key]):
            raise ValueError("%s must be a plain public contact identifier" % key)
    urls = [("EMPLOYER_URL", cfg.get("EMPLOYER_URL"))]
    alumni = cfg.get("ALUMNI_OF", [])
    if not isinstance(alumni, list) or any(not isinstance(item, dict) for item in alumni):
        raise ValueError("ALUMNI_OF must be an array of objects")
    urls.extend(("ALUMNI_OF url", item.get("url")) for item in alumni)
    for key, value in urls:
        try:
            parsed = urlsplit(value) if isinstance(value, str) else None
            valid = (parsed and parsed.scheme in {"https", "http"} and parsed.hostname
                     and not parsed.username and not parsed.password and not parsed.fragment
                     and not any(c.isspace() or ord(c) < 32 or c in '\\<>"' for c in value))
            if parsed:
                parsed.port
        except ValueError:
            valid = False
        if not valid:
            raise ValueError("%s must be an absolute HTTP(S) URL without credentials or fragment" % key)


def fill(text, cfg):
    """Replace {{KEY}} with the config value. Scalars only; lists are handled by the caller.

    User-configured values are HTML-escaped because {{KEY}} substitutions
    can land inside HTML attributes. JSON_LD is generated by json_block(),
    which serializes and script-escapes the complete document, so it must
    be inserted without HTML entity encoding.
    """
    import html as _html
    def sub(m):
        key = m.group(1)
        val = cfg.get(key)
        if val is None:
            return m.group(0)          # leave unknown tokens visible rather than blanking them
        if isinstance(val, (list, dict)):
            return m.group(0)
        if isinstance(val, ScriptSafeJson):
            return str(val)
        return _html.escape(str(val), quote=True)
    return re.sub(r"\{\{([A-Z0-9_]+)\}\}", sub, text)


def json_block(cfg):
    """Generate the complete JSON-LD document with script-safe JSON encoding."""
    domain_url = "https://%s/" % cfg["DOMAIN"]
    person_id = "%s#person" % domain_url
    employer_id = "%s#employer" % domain_url
    same_as = [
        "https://www.linkedin.com/in/%s" % cfg["LINKEDIN_SLUG"],
        "https://x.com/%s" % cfg["X_HANDLE"],
    ]
    document = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Person",
                "@id": person_id,
                "name": cfg["FULL_NAME"],
                "givenName": cfg["GIVEN_NAME"],
                "familyName": cfg["FAMILY_NAME"],
                "url": domain_url,
                "mainEntityOfPage": domain_url,
                "jobTitle": cfg["JOB_TITLE"],
                "email": cfg["EMAIL"],
                "description": cfg["SUMMARY"],
                "worksFor": {"@id": employer_id},
                "homeLocation": {
                    "@type": "Place",
                    "address": {
                        "@type": "PostalAddress",
                        "addressLocality": cfg["CITY"],
                        "addressCountry": cfg["COUNTRY_CODE"],
                    },
                },
                "nationality": {"@type": "Country", "name": cfg["COUNTRY_NAME"]},
                "knowsAbout": cfg.get("KNOWS_ABOUT", []),
                "alumniOf": [
                    {
                        "@type": "Organization",
                        "name": alumnus.get("name", ""),
                        "sameAs": alumnus.get("url", ""),
                    }
                    for alumnus in cfg.get("ALUMNI_OF", [])
                ],
                "hasOccupation": {
                    "@type": "Occupation",
                    "name": cfg["JOB_TITLE"],
                    "occupationLocation": {"@type": "City", "name": cfg["CITY"]},
                },
                "sameAs": same_as,
            },
            {
                "@type": "Organization",
                "@id": employer_id,
                "name": cfg["EMPLOYER"],
                "url": cfg["EMPLOYER_URL"],
                "description": cfg["EMPLOYER_DESC"],
                "address": {
                    "@type": "PostalAddress",
                    "addressLocality": cfg["CITY"],
                    "addressCountry": cfg["COUNTRY_CODE"],
                },
            },
            {
                "@type": "ProfilePage",
                "@id": "%s#profilepage" % domain_url,
                "url": domain_url,
                "name": "%s: %s, %s"
                % (cfg["FULL_NAME"], cfg["JOB_TITLE"], cfg["EMPLOYER"]),
                "mainEntity": {"@id": person_id},
                "dateModified": cfg["LAST_UPDATED"],
            },
            {
                "@type": "FAQPage",
                "@id": "%s#faq" % domain_url,
                "url": domain_url,
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": "Who is %s?" % cfg["FULL_NAME"],
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": cfg["SUMMARY"],
                        },
                    },
                    {
                        "@type": "Question",
                        "name": "What is %s's job title?" % cfg["FULL_NAME"],
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "%s at %s."
                            % (cfg["JOB_TITLE"], cfg["EMPLOYER"]),
                        },
                    },
                    {
                        "@type": "Question",
                        "name": "How should I contact %s?" % cfg["FULL_NAME"],
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": (
                                "%s for business, partnerships and integrations. "
                                "LinkedIn at https://www.linkedin.com/in/%s. "
                                "Public discussion on X at @%s."
                            )
                            % (cfg["EMAIL"], cfg["LINKEDIN_SLUG"], cfg["X_HANDLE"]),
                        },
                    },
                ],
            },
        ],
    }
    encoded = json.dumps(document, indent=2, ensure_ascii=False)
    encoded = (
        encoded.replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )
    return {
        "JSON_LD": ScriptSafeJson(encoded),
    }


def is_link_like(path):
    """Return whether path can redirect traversal outside the template tree."""
    if os.path.islink(path):
        return True
    isjunction = getattr(os.path, "isjunction", None)
    if isjunction and isjunction(path):
        return True
    attributes = getattr(os.lstat(path), "st_file_attributes", 0)
    return bool(attributes & WINDOWS_REPARSE_POINT)


def build_site(template_dir, out_dir, cfg):
    """Build a complete site into an empty staging directory."""
    cfg = dict(cfg, EMAIL_URI=quote(cfg.get("EMAIL", ""), safe="@"))
    if not os.path.lexists(template_dir):
        raise OSError("template path does not exist: %s" % template_dir)
    if is_link_like(template_dir):
        raise OSError("refusing to build from link-like template root: %s" % template_dir)
    if not os.path.isdir(template_dir):
        raise OSError("template path is not a directory: %s" % template_dir)

    from build_inventory import MAX_FILES, MAX_FILE_BYTES, MAX_TOTAL_BYTES
    n, total_bytes = 0, 0
    for dirpath, dirs, files in os.walk(template_dir):
        for dirname in dirs:
            path = os.path.join(dirpath, dirname)
            if is_link_like(path):
                raise OSError(
                    "refusing to build from link-like template path: %s"
                    % os.path.relpath(path, template_dir)
                )
        rel = os.path.relpath(dirpath, template_dir)
        target_dir = out_dir if rel == "." else os.path.join(out_dir, rel)
        os.makedirs(target_dir, exist_ok=True)
        for f in files:
            src = os.path.join(dirpath, f)
            dst = os.path.join(target_dir, f)
            relative = os.path.relpath(src, template_dir)
            if is_link_like(src):
                raise OSError(
                    "refusing to build from link-like template path: %s" % relative
                )
            if not os.path.isfile(src):
                raise OSError(
                    "refusing to build from non-regular template path: %s" % relative
                )
            size = os.path.getsize(src)
            total_bytes += size
            if n >= MAX_FILES or size > MAX_FILE_BYTES or total_bytes > MAX_TOTAL_BYTES:
                raise ValueError("template exceeds the file count or byte budget")
            if f.lower().endswith((".png", ".jpg", ".jpeg", ".gif", ".ico", ".webp", ".pdf")):
                with open(src, "rb") as a, open(dst, "wb") as b:
                    b.write(a.read())
            else:
                with io.open(src, encoding="utf-8") as source:
                    t = source.read()
                with io.open(dst, "w", encoding="utf-8", newline="") as output:
                    output.write(fill(t, cfg))
            n += 1

    print("  filled %d files into site/" % n)

    leftover = {}
    for dirpath, _, files in os.walk(out_dir):
        for f in files:
            if not f.endswith((".md", ".txt", ".html", ".xml", ".json")):
                continue
            with io.open(os.path.join(dirpath, f), encoding="utf-8", errors="ignore") as source:
                t = source.read()
            for m in re.finditer(r"\{\{([A-Z0-9_]+)\}\}", t):
                leftover.setdefault(m.group(1), set()).add(f)
    if leftover:
        print("\n  UNFILLED PLACEHOLDERS (add these keys to site.config.json):")
        for k, where in sorted(leftover.items()):
            print("    {{%s}}  in %s" % (k, ", ".join(sorted(where))[:60]))
    else:
        print("  no unfilled placeholders")

    # steps 2 through 6
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import a2a_agent_card
    a2a_agent_card.publish_agent_card(ROOT, out_dir, cfg)
    import build_llms_index
    if os.path.isfile(os.path.join(out_dir, "llms.txt")):
        build_llms_index.run(out_dir, cfg)
    import build_writing_html
    build_writing_html.run(out_dir, cfg)
    import build_catalog
    build_catalog.run(out_dir, cfg)
    import build_llms_full
    build_llms_full.run(out_dir, cfg)
    import build_sitemap
    build_sitemap.run(out_dir, cfg)
    import build_inventory
    build_inventory.run(out_dir, cfg)


def replace_output(staging_dir, output_dir):
    """Replace only output_dir, restoring the prior build if promotion fails."""
    parent = os.path.dirname(output_dir)
    backup = None
    backup_slot = None
    if os.path.lexists(output_dir):
        if is_link_like(output_dir) or not os.path.isdir(output_dir):
            raise OSError("refusing to replace site/ because it is not a real directory")
        backup_slot = tempfile.mkdtemp(prefix=".site-backup-", dir=parent)
        backup = os.path.join(backup_slot, "site")
        try:
            os.replace(output_dir, backup)
        except Exception:
            try:
                shutil.rmtree(backup_slot)
            except OSError as exc:
                print(
                    "  WARNING: the previous site was preserved, but an empty "
                    "backup slot could not be removed at %s: %s" % (backup_slot, exc),
                    file=sys.stderr,
                )
            raise
    try:
        os.replace(staging_dir, output_dir)
    except Exception:
        if backup is not None:
            try:
                os.replace(backup, output_dir)
            except Exception as restore_exc:
                raise OSError(
                    "site promotion failed and the previous site could not be "
                    "restored; recover it from %s" % backup
                ) from restore_exc
            try:
                os.rmdir(backup_slot)
            except OSError as exc:
                print(
                    "  WARNING: the previous site was restored, but an empty "
                    "backup slot could not be removed at %s: %s" % (backup_slot, exc),
                    file=sys.stderr,
                )
        raise
    if backup_slot is not None:
        try:
            shutil.rmtree(backup_slot)
        except OSError as exc:
            print(
                "  WARNING: new site was promoted, but the previous output "
                "could not be removed at %s: %s" % (backup_slot, exc),
                file=sys.stderr,
            )


def paths_overlap(first, second, path_module=os.path):
    """Compare resolved directories, allowing disjoint Windows drives."""
    first, second = path_module.normcase(first), path_module.normcase(second)
    try:
        common = path_module.commonpath([first, second])
    except ValueError:
        # Resolved paths are absolute; different drives have no common path.
        return False
    return common in {first, second}


def build_site_staged(template_dir, output_dir, cfg):
    """Generate in a sibling staging directory, then promote completed output."""
    template_real, output_real = os.path.realpath(template_dir), os.path.realpath(output_dir)
    if paths_overlap(template_real, output_real):
        raise ValueError("template and output directories must not overlap")
    parent = os.path.dirname(output_dir)
    os.makedirs(parent, exist_ok=True)
    staging = tempfile.mkdtemp(prefix=".site-build-", dir=parent)
    try:
        build_site(template_dir, staging, cfg)
        replace_output(staging, output_dir)
    finally:
        build_failed = sys.exc_info()[0] is not None
        if os.path.isdir(staging):
            try:
                shutil.rmtree(staging)
            except OSError as exc:
                if not build_failed:
                    raise
                print(
                    "  WARNING: the build failed, and its staging directory "
                    "could not be removed at %s: %s" % (staging, exc),
                    file=sys.stderr,
                )


def main():
    cfg = load_config()
    cfg = dict(cfg, **json_block(cfg))

    if not os.path.isdir(TEMPLATE):
        sys.exit("No template/ directory found.")

    build_site_staged(TEMPLATE, OUT, cfg)

    print("\n  done. Next: python scripts/quality_check.py")


if __name__ == "__main__":
    main()
