# Adversarial quality check. Run before every deploy.
#
# Reads site/ (built by scripts/build.py) and site.config.json.
#
#   py quality-check.py           local source files only (fast)
#   py quality-check.py --live    also verify every link and sitemap URL over HTTP
#
# Design note: an earlier version of this reported five failures that were all
# its own false positives. A checker that cries wolf trains you to ignore it,
# which is worse than having none. Every rule below is therefore scoped to the
# thing it actually forbids, and the deliberate exceptions are named in code.
import io, os, re, json, subprocess, sys
import xml.etree.ElementTree as ET
from collections import Counter

from build_sitemap import public_urls, validate_last_updated

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = os.path.join(REPO, "site")
_cfg_path = os.path.join(REPO, "site.config.json")
if os.path.exists(_cfg_path):
    with io.open(_cfg_path, encoding="utf-8") as config_file:
        _cfg = json.load(config_file)
else:
    _cfg = {}
DOMAIN = _cfg.get("DOMAIN", "example.com")
EMAIL = _cfg.get("EMAIL", "")
JOB_TITLE = _cfg.get("JOB_TITLE", "")
LIVE = "--live" in sys.argv
SKIP_FILES = {"README.md", "PROMOTION.md", "RECOMMENDATIONS.md", "MONITORING.md"}
# llms-full.txt is generated by concatenation: any violation in it mirrors a
# source file and would be double-counted, so it is scanned separately at the end.
GENERATED = {"llms-full.txt"}

fails, warns = [], []

def sources(include_generated=False):
    out = []
    for f in sorted(os.listdir(R)):
        if f.endswith((".md", ".txt", ".html", ".xml")) and f not in SKIP_FILES:
            if f in GENERATED and not include_generated:
                continue
            out.append((f, os.path.join(R, f)))
    w = os.path.join(R, "writing")
    for f in sorted(os.listdir(w)):
        if f.endswith((".md", ".html")):
            out.append(("writing/" + f, os.path.join(w, f)))
    return out

def read(p):
    with io.open(p, encoding="utf-8", errors="ignore") as source:
        return source.read()

def head(msg):
    print("\n" + "=" * 68 + "\n" + msg + "\n" + "=" * 68)

# Deliberate exceptions, each with its reason.
ALLOWED = [
    # Add deliberate exceptions here, each with the reason it is allowed.
    # Example, from the reference site: Visa's own programme name is a proper
    # noun, so the American-English rule does not apply to it.
    #   (r"Agentic Ready Programme", "Visa proper noun"),
]

# Strings that must never appear anywhere on the site. Fill this in.
# The reference site used it to keep an undisclosed alt account, and the topics
# that would identify it, off every page. Naming the handle is not enough:
# a description of its subject matter is itself a search key.
FORBIDDEN = []

def url_spans(text):
    """URLs are identifiers, not prose. Spelling rules do not apply inside them."""
    return [(m.start(), m.end()) for m in re.finditer(r"https?://[^\s)\"'<>\]]+", text)]

def allowed_at(text, pos, spans=None):
    if spans is None:
        spans = url_spans(text)
    for a, b in spans:
        if a <= pos < b:
            return True
    for pat, _ in ALLOWED:
        for m in re.finditer(pat, text):
            if m.start() - 120 <= pos <= m.end() + 120:
                return True
    return False

head("1. RULE COMPLIANCE")
RULES = [
    ("em/en dash", r"[–—]|&mdash;|&ndash;"),
    # Add your own forbidden strings here: an alt handle, a former employer
    # you do not want surfaced, a project name under embargo.
    ("forbidden strings", r"(?i)" + "|".join(FORBIDDEN) if FORBIDDEN else r"(?!x)x"),
    # Only words where American English genuinely differs. A blanket [a-z]+ised
    # is wrong: revise, advise, promise, comprise and friends are -ise in BOTH
    # dialects, and an earlier version flagged "revised" as a British spelling.
    ("British spelling", r"(?i)\b(licence|behaviour|colour|favour|centre|defence|offence|"
                         r"programme|modelled|modelling|labelled|cancelled|travelled|"
                         r"analyse|analysed|organis(e|ed|ing|ation)|optimis(e|ed|ing|ation)|"
                         r"realis(e|ed|ing)|recognis(e|ed|ing)|prioritis(e|ed|ing)|"
                         r"standardis(e|ed|ing|ation)|summaris(e|ed|ing)|specialis(e|ed)|"
                         r"minimis(e|ed)|maximis(e|ed)|utilis(e|ed)|capitalis(e|ed)|"
                         r"tokenis(e|ed|ation)|monetis(e|ed)|centralis(e|ed)|"
                         r"decentralis(e|ed)|collateralis(e|ed)|normalis(e|ed))\b"),
]
for name, pat in RULES:
    hits = []
    for rel, p in sources():
        t = read(p)
        for m in re.finditer(pat, t):
            if allowed_at(t, m.start()):
                continue
            hits.append("%s:%s" % (rel, m.group(0)))
    if hits:
        fails.append("%s (%d)" % (name, len(hits)))
        print("  FAIL %-28s %d  %s" % (name, len(hits), hits[:4]))
    else:
        print("  ok   %-28s 0" % name)

head("2. CROSS-FILE FACT CONSISTENCY")
FACTS = [
    ("job title", r"(?i)\b(%s)\b" % re.escape(JOB_TITLE) if JOB_TITLE else r"(?!x)x", {JOB_TITLE.lower()}),
    ("email", r"[a-zA-Z0-9._%%+-]+@" + re.escape(DOMAIN), {EMAIL}),
]
for name, pat, allowed in FACTS:
    found = {}
    for rel, p in sources():
        for m in re.finditer(pat, read(p)):
            v = m.group(1) if m.groups() else m.group(0)
            found.setdefault(v, []).append(rel)
    # compare case-insensitively: a title is the same title in any casing
    allowed = {a.lower() for a in allowed if a}
    bad = {k: v[:2] for k, v in found.items() if k.lower() not in allowed}
    if bad:
        fails.append("%s: %s" % (name, list(bad)))
        print("  FAIL %-18s unexpected: %s" % (name, bad))
    else:
        print("  ok   %-18s %s" % (name, sorted(found)))

head("3. STRUCTURED DATA")
for rel, p in sources():
    if not rel.endswith(".html") or rel == "404.html":
        continue
    for m in re.finditer(r'(?s)<script type="application/ld\+json">(.*?)</script>', read(p)):
        try:
            d = json.loads(m.group(1))
            if isinstance(d, dict) and "@graph" in d:
                print("  ok   %-40s %s" % (rel, [n.get("@type") for n in d["@graph"]]))
            else:
                linked = d.get("author", {}).get("@id") == "" + "https://" + DOMAIN + "/#person"
                print("  %-4s %-40s %s author->#person" % ("ok" if linked else "FAIL", rel, d.get("@type")))
                if not linked:
                    fails.append("%s author not linked to #person" % rel)
        except Exception as e:
            fails.append("%s JSON-LD invalid" % rel)
            print("  FAIL %-40s %s" % (rel, e))

head("4. LAST-UPDATED DATES")
configured_lastmod = _cfg.get("LAST_UPDATED")
try:
    expected_lastmod = validate_last_updated(configured_lastmod)
    print("  ok   site.config.json LAST_UPDATED is %s" % expected_lastmod)
except ValueError as exc:
    expected_lastmod = None
    fails.append(str(exc))
    print("  FAIL %s" % exc)
for rel, p in sources():
    if not rel.endswith(".md"):
        continue
    match = re.search(r"Last updated:\s*(\S+)", read(p))
    if not match:
        warns.append("%s has no 'Last updated'" % rel)
        print("  WARN %-40s no Last updated line" % rel)
        continue
    page_lastmod = match.group(1).rstrip(".,;:)")
    try:
        validate_last_updated(page_lastmod)
    except ValueError:
        fails.append("%s has an invalid Last updated date" % rel)
        print("  FAIL %-40s invalid Last updated date" % rel)
print("  (files with a date are not listed)")

head("5. GENERATED FILE IS IN SYNC")
lf = os.path.join(R, "llms-full.txt")
if os.path.exists(lf):
    t = read(lf)
    missing = [rel for rel, p in sources()
               if rel.endswith(".md") and rel not in ("404.md",)
               and read(p)[:60].strip().split("\n")[0] not in t]
    if missing:
        fails.append("llms-full.txt missing: %s" % missing)
        print("  FAIL llms-full.txt is stale, missing: %s" % missing)
    else:
        print("  ok   llms-full.txt contains every .md source")

head("6. SITEMAP MATCHES BUILD OUTPUT")
sitemap_path = os.path.join(R, "sitemap.xml")
try:
    root = ET.parse(sitemap_path).getroot()
    entries = root.findall("{http://www.sitemaps.org/schemas/sitemap/0.9}url")
    actual_urls = [entry.findtext("{http://www.sitemaps.org/schemas/sitemap/0.9}loc", "") for entry in entries]
    expected_urls = public_urls(R, DOMAIN)
    duplicates = sorted(url for url, count in Counter(actual_urls).items() if count > 1)
    missing = sorted(set(expected_urls) - set(actual_urls))
    stale = sorted(set(actual_urls) - set(expected_urls))
    lastmods = [entry.findtext("{http://www.sitemaps.org/schemas/sitemap/0.9}lastmod", "") for entry in entries]
    malformed_lastmod = [
        url for url, value in zip(actual_urls, lastmods)
        if value and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value)
    ]
    for url, value in zip(actual_urls, lastmods):
        if not value or url in malformed_lastmod:
            continue
        try:
            validate_last_updated(value)
        except ValueError:
            malformed_lastmod.append(url)
    bad_lastmod = [
        url for url, value in zip(actual_urls, lastmods) if value != expected_lastmod
    ] if expected_lastmod is not None else []
    unexpected_lastmod = [
        url for url, value in zip(actual_urls, lastmods) if value
    ] if expected_lastmod is None else []
    if duplicates:
        fails.append("sitemap.xml has duplicate URLs: %s" % duplicates)
        print("  FAIL duplicate URLs: %s" % duplicates)
    if missing:
        fails.append("sitemap.xml missing built files: %s" % missing)
        print("  FAIL missing built files: %s" % missing)
    if stale:
        fails.append("sitemap.xml has URLs without built files: %s" % stale)
        print("  FAIL URLs without built files: %s" % stale)
    if malformed_lastmod:
        malformed_lastmod = sorted(set(malformed_lastmod))
        fails.append("sitemap.xml has malformed lastmod dates: %s" % malformed_lastmod)
        print("  FAIL malformed lastmod dates: %s" % malformed_lastmod)
    if bad_lastmod:
        fails.append("sitemap.xml lastmod does not match LAST_UPDATED: %s" % bad_lastmod)
        print("  FAIL lastmod differs from LAST_UPDATED: %s" % bad_lastmod)
    if unexpected_lastmod:
        fails.append("sitemap.xml has lastmod dates without a valid LAST_UPDATED: %s" % unexpected_lastmod)
        print("  FAIL unexpected lastmod without valid LAST_UPDATED: %s" % unexpected_lastmod)
    if not duplicates and not missing and not stale and not malformed_lastmod and not bad_lastmod and not unexpected_lastmod:
        print("  ok   %d sitemap URLs match public build artifacts" % len(actual_urls))
        if expected_lastmod is not None:
            print("  ok   every lastmod matches LAST_UPDATED (%s)" % expected_lastmod)
except (ET.ParseError, OSError) as exc:
    fails.append("sitemap.xml is missing or invalid: %s" % exc)
    print("  FAIL sitemap.xml is missing or invalid: %s" % exc)

if LIVE:
    head("7. LIVE: LINKS AND SITEMAP")
    links = set()
    for rel, p in sources():
        for m in re.finditer(r"https://" + re.escape(DOMAIN) + r"(/[^\s)\"'<>\]]*)?", read(p)):
            u = (m.group(1) or "/").rstrip(".,;:)")   # strip trailing punctuation
            links.add(u)
    sm = read(os.path.join(R, "sitemap.xml"))
    links |= set(re.findall(r"<loc>https://" + re.escape(DOMAIN) + r"(/[^<]*)</loc>", sm))
    print("  checking %d distinct URLs..." % len(links))
    bad = []
    for u in sorted(links):
        r = subprocess.run(["curl.exe", "-sS", "-o", os.devnull, "-w", "%{http_code}",
                            "--max-time", "20", "https://" + DOMAIN + u],
                           capture_output=True, text=True)
        if r.stdout.strip() != "200":
            bad.append((u, r.stdout.strip()))
    for u, c in bad:
        fails.append("link %s -> %s" % (u, c))
        print("  FAIL %-50s %s" % (u, c))
    if not bad:
        print("  ok   every URL resolves 200")

    # ownership proofs: deleting any of these un-verifies the site
    print("\n  ownership proofs:")
    for u in _cfg.get("verification_paths", []):
        r = subprocess.run(["curl.exe", "-sS", "-o", os.devnull, "-w", "%{http_code}",
                            "--max-time", "20", "https://" + DOMAIN + u],
                           capture_output=True, text=True)
        ok = r.stdout.strip() == "200"
        if not ok:
            fails.append("ownership proof missing: %s" % u)
        print("    %-4s %s" % ("ok" if ok else "FAIL", u))

    # markdown must render inline, not download
    r = subprocess.run(["curl.exe", "-sS", "-o", os.devnull, "-D", "-",
                        "--max-time", "20", "https://" + DOMAIN + "/profile.md"],
                       capture_output=True, text=True)
    inline = "text/markdown" in r.stdout.lower() and "inline" in r.stdout.lower()
    if not inline:
        fails.append("profile.md not served inline: .htaccess may not be applying (check chmod 644)")
    print("\n  %-4s markdown served inline as text/markdown" % ("ok" if inline else "FAIL"))

head("SUMMARY")
print("  FAILURES: %d" % len(fails))
for f in fails:
    print("    - %s" % f)
print("  WARNINGS: %d" % len(warns))
for w in warns:
    print("    - %s" % w)
sys.exit(1 if fails else 0)
